import time
import sys
print("START SOMETHING")
# sys.stdout.flush()
time.sleep(1)
print("Text 1")
time.sleep(1)
print("Text 2")
time.sleep(1)
print("Text 3")
time.sleep(1)
print("Text 4")
time.sleep(1)
print("Text 5")
time.sleep(1)
print("Text 6")
time.sleep(1)
print("Text 7")
time.sleep(1)
print("Text 8")
time.sleep(1)
print("Text 8")
# sys.stdout.flush()
print("END SOMETHING")